=== AbrahamFB/Tecnolog-as-Web/Prácticas/p12/10-catalogovod.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="CatalogoVOD" type="cuentaCatalogoVODType"/>
    <xsd:element name="cuenta" type="cuentaType"/>
    <xsd:element name="perfiles" type="perfilesType"/>
    <xsd:element name="perfil" type="perfilType"/>
    <xsd:element name="contenido" type="contenidoType"/>
    <xsd:element name="peliculas" type="peliculasType"/>
    <xsd:element name="programas" type="programasType"/>
    
    <xsd:complexType name="cuentaCatalogoVODType">
        <xsd:sequence>
            <xsd:element ref="cuenta" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="cuentaType">
        <xsd:sequence>
            <xsd:element ref="perfiles" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="correo" type="emailType"/>
        <xsd:attribute name="tipo" type="tipoType"/>
        <xsd:attribute name="tdc" type="tdcType"/>
    </xsd:complexType>
    
    <xsd:simpleType name="emailType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-z|0-9]+\.[a-z|0-9]+@[a-z]+\.[a-z]{2,3}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="tipoType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="basica"/>
            <xsd:enumeration value="premium"/>
            <xsd:enumeration value="familiar"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="tdcType">
        <xsd:restriction base="listIntType">
            <xsd:length value="4"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="listIntType">
        <xsd:list itemType="xsd:int"/>
    </xsd:simpleType>
    
    <xsd:complexType name="perfilesType">
        <xsd:sequence>
            <xsd:element ref="perfil" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="limite" use="optional"/>
    </xsd:complexType>
    
    <xsd:complexType name="perfilType">
        <xsd:sequence>
            <xsd:element ref="contenido" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="usuario" type="xsd:string" use="required"/>
        <xsd:attribute name="idioma" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="contenidoType">
        <xsd:all>
            <xsd:element ref="peliculas" maxOccurs="1" minOccurs="0"/>
            <xsd:element ref="programas" maxOccurs="1" minOccurs="0"/>
        </xsd:all>
        <xsd:attribute name="clasificacion" type="clasificacionType" use="required"/>
    </xsd:complexType>
    
    <xsd:simpleType name="clasificacionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="A"/>
            <xsd:enumeration value="B"/>
            <xsd:enumeration value="B15"/>
            <xsd:enumeration value="C"/>
            <xsd:enumeration value="D"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="peliculasType">
        <xsd:sequence>
            <xsd:element name="genero" type="generoPeliculasType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="programasType">
        <xsd:sequence>
            <xsd:element name="genero" type="generoProgramasType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="generoPeliculasType">
        <xsd:sequence>
            <xsd:element name="titulo" type="tituloPeliculasType" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="nombre" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="generoProgramasType">
        <xsd:sequence>
            <xsd:element name="titulo" type="tituloProgramasType" maxOccurs="unbounded">
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="nombre" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="tituloPeliculasType" mixed="true">
        <xsd:attribute name="duracion" type="xsd:time" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="tituloProgramasType" mixed="true">
        <xsd:attribute name="temporada" type="xsd:integer" use="optional"/>
        <xsd:attribute name="capitulo" type="xsd:integer" use="required"/>
    </xsd:complexType>
    
</xsd:schema>

=== AbrahamFB/Tecnolog-as-Web/Prácticas/p013/10-catalogovod.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="link.xsl"?>

<CatalogoVOD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="10-catalogovod.xsd">
    <cuenta correo="mark.zuckerberg@facebook.com" tipo="familiar" tdc="4772 1330 1233 7470">
        <perfiles limite="4">
            <perfil usuario="Abraham" idioma="espaniol">
                <contenido clasificacion="B">
                    <peliculas>
                        <genero nombre="Infantil">
                            <titulo duracion="01:03:00">Mi villano favorito</titulo>
                            <titulo duracion="02:13:00">Bob Esponja</titulo>
                        </genero>
                        <genero nombre="ReflexiÃ³n">
                            <titulo duracion="01:50:00">Me llaman radio</titulo>
                            <titulo duracion="01:01:00">Mi nombre es Khan</titulo>
                        </genero>
                    </peliculas>
                    <programas>
                        <genero nombre="Entretenimiento">
                            <titulo temporada="1" capitulo="10">Mi pareja puede</titulo>
                            <titulo temporada="1" capitulo="12">El socio</titulo>
                        </genero>
                        <genero nombre="comedia">
                            <titulo temporada="2" capitulo="1">Impractical Jokers</titulo>
                            <titulo temporada="11" capitulo="3">Malcom In The Middle</titulo>
                        </genero>
                    </programas>
                </contenido>
            </perfil>
            <perfil usuario="Mark" idioma="english">
                <contenido clasificacion="C">
                    <peliculas>
                        <genero nombre="Terror">
                            <titulo duracion="02:03:00">World War Z</titulo>
                            <titulo duracion="01:33:00">Chernobyl Diaries</titulo>
                        </genero>
                        <genero nombre="Science fiction">
                            <titulo duracion="01:55:00">I, Robot</titulo>
                            <titulo duracion="02:19:00">Ready Player One</titulo>
                        </genero>
                    </peliculas>
                </contenido>
            </perfil>
            <perfil usuario="Priscilla" idioma="chinese">
                <contenido clasificacion="B15">
                    <programas>
                        <genero nombre="Doramas">
                            <titulo temporada="1" capitulo="11">The Secret Garden</titulo>
                            <titulo temporada="1" capitulo="13">Goblin: The Great and Lonely
                                God</titulo>
                        </genero>
                        <genero nombre="Comedy">
                            <titulo temporada="9" capitulo="1">The Big Bang Theory</titulo>
                            <titulo temporada="11" capitulo="3">Malcom In The Middle</titulo>
                        </genero>
                    </programas>
                </contenido>
            </perfil>
            <perfil usuario="Kids" idioma="english">
                <contenido clasificacion="A">
                    <peliculas>
                        <genero nombre="Animation">
                            <titulo duracion="01:48:00">Big Hero 6</titulo>
                            <titulo duracion="01:35:00">Toy Story 2</titulo>
                        </genero>
                        <genero nombre="Cartoons">
                            <titulo duracion="01:33:00">Hercules</titulo>
                            <titulo duracion="01:28:00">Mulan</titulo>
                        </genero>
                    </peliculas>
                    <programas>
                        <genero nombre="Cartoons">
                            <titulo temporada="8" capitulo="3">The Bare Bears</titulo>
                            <titulo temporada="5" capitulo="1">Teen Titans GO</titulo>
                        </genero>
                        <genero nombre="Comedy">
                            <titulo temporada="2" capitulo="7">San &amp; Cat</titulo>
                            <titulo temporada="1" capitulo="11">iCarly</titulo>
                        </genero>
                    </programas>
                </contenido>
            </perfil>
        </perfiles>
    </cuenta>
</CatalogoVOD>
