=== AbrahamFB/Tecnolog-as-Web/Prácticas/p08/dtd.dtd
<!ELEMENT pedidos (pedido)*>
<!ELEMENT pedido (cod_pedido|sucursal|direccion|nombre_trabajador|fecha_pedido|observaciones|plazo_revision|codigo_articulo|unidades|precio_unidad|observaciones_articulo)*>
<!ELEMENT cod_pedido (#PCDATA)>
<!ELEMENT sucursal (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombre_trabajador (#PCDATA)>
<!ELEMENT fecha_pedido (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT plazo_revision (#PCDATA)>
<!ELEMENT codigo_articulo (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio_unidad (#PCDATA) >
<!ELEMENT observaciones_articulo (#PCDATA)>

=== AbrahamFB/Tecnolog-as-Web/Prácticas/p08/s.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pedidos SYSTEM "dtd.dtd">

<pedidos>
        <pedido>
                <cod_pedido></cod_pedido>
                <sucursal></sucursal>
                <direccion></direccion>
                <nombre_trabajador></nombre_trabajador>
                <fecha_pedido></fecha_pedido>
                <observaciones></observaciones>
                <plazo_revision></plazo_revision>
                <codigo_articulo></codigo_articulo>
                <unidades></unidades>
                <precio_unidad></precio_unidad>
                <observaciones_articulo></observaciones_articulo>
        </pedido>
</pedidos>
